RETURN_SOURCE_DOCUMENTS: True
VECTOR_COUNT: 2
CHUNK_SIZE: 500
CHUNK_OVERLAP: 50
DATA_PATH: 'data/'
DB_FAISS_PATH: 'vectorstore/db_faiss'
MODEL_TYPE: 'llama'
MODEL_BIN_PATH: 'models/orca-mini-3b-gguf2-q4_0.gguf'
MODEL_URL: 'https://gpt4all.io/models/gguf/orca-mini-3b-gguf2-q4_0.gguf'
MAX_NEW_TOKENS: 256
TEMPERATURE: 0.01