name: Unit Tests Push

on: push 

jobs:
  unit-testing:
    runs-on: ubuntu-latest 
    
    steps:
    - name : Checkout code
      uses : actions/checkout@v4
      
    - name : Install Packages 
      run : pip install -r requirements.txt
      
    - name: Test with unittest
      run: python -m unittest discover -s .  -p '*_test.py'