name: Unit Tests Push

on: push 

jobs:
  run-unit-tests:
    runs-on: ubuntu-latest 
    
    steps:
    - name : Checkout code
      uses : actions/checkout@v4
    - name : Download model
      run: |
        pwd
        url="https://gpt4all.io/models/gguf/orca-mini-3b-gguf2-q4_0.gguf"
        curl -o ./models/orca-mini-3b-gguf2-q4_0.gguf "$url"
        tree
    - name : Install Packages 
      run : pip install -r requirements.txt

      
    - name: Test with unittest
      run: python -m unittest discover -s .  -p '*_test.py'