name: Unit Tests Push

on: push 

jobs:
  run-unit-tests:
    runs-on: ubuntu-latest 
    
    steps:
    - name: Install Redis
      run: |
        sudo apt install lsb-release curl gpg
        curl -fsSL https://packages.redis.io/gpg | sudo gpg --dearmor -o /usr/share/keyrings/redis-archive-keyring.gpg

        echo "deb [signed-by=/usr/share/keyrings/redis-archive-keyring.gpg] https://packages.redis.io/deb $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/redis.list

        sudo apt-get update
        redis-server &  
    - name : Checkout code
      uses : actions/checkout@v4
    - name : Download model
      run: |
        pwd
        url="https://gpt4all.io/models/gguf/orca-mini-3b-gguf2-q4_0.gguf"
        curl -o ./models/orca-mini-3b-gguf2-q4_0.gguf "$url"
        tree
    - name : Install Packages 
      run : pip install -r requirements.txt

    - name: Build Faiss DB
      run: |
        python3 ./database/db.py
      
    - name: Test with unittest
      run: python -m unittest discover -s .  -p '*_test.py'