on:
    push:      
    pull_request:
  
  name: Pysa
  
  jobs:
    pysa:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
  
        - name: Run Pysa Action
          uses: facebook/pysa-action
          with:
            repo-directory: './'
            requirements-path: 'requirements.txt'
            infer-types: true
            include-default-sapp-filters: true
